# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Zahari A. Romanov
title: 
email: zahariromanov@pm.me
website: https://zahariromanov.github.io/ 

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  zahariromanov
stackoverflow_username: "zahariromanov"
# kaggle_username: "zahariromanov"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: zahariromanov
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hello World! My name is Zahari Romanov; I am an American Veteran Small-Business Owner and Developer working to make the next generation of technical vision a reality. 

  I am most skilled in and continuously learning more about: <mark>Full-Stack Development</mark>, <mark>Python</mark>, building WebApps with <mark>Flask</mark> and <mark>Artificial Intelligence</mark> development. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: Resume
        link: https://zahariromanov.github.io/
        # link_text: Project Website
        additional_links:
          - title:  zahariromanov.github.io repo
            icon: fab fa-github
            url: https://zahariromanov.github.io/
          # - title:  Github page for project (eg. zahariromanov.github.io)
          #   icon: fab fa-github
          #   url: Link to project (eg. https://zahariromanov.github.io/)
        quote: >
          This is an interactive resume to showcase my portfolio and credentials.
        description: | # this will include new lines to allow paragraphs
          I am building this project as a resume and portfolio for potential employers.
      - layout: left
        title: Python Projects
        link: https://github.com/zahariromanov/Python-Projects
        additional_links:
        - title: Python Projects
          icon: fab fa-github
          url: https://github.com/zahariromanov/Python-Projects
        quote: >
            This is a repository of various Python Projects ranging from simple scripts to Flask Web Pages as well as Artificial Intelligence Projects and other Tensorflow Projects.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Department of Defense
        link: goarmy.com
        link_text: GoArmy
        sub_title: Enlisted
        caption: January 2013 - July 2020
        quote: >
          Providing Security and Logistics support in the Commonwealth of Virginia and the United States of America.
        description: | # this will include new lines to allow paragraphs
            I enlisted in High School as a Military Police Officer and later transitioned into being a Motor Transport Operator.

      - layout: left
        title: Amazon.com
        link: amazon.com
        link_text: Amazon
        sub_title: Business Group Associate
        caption: February 2021 - February 2022
        quote: >
          Providing Support and Analysis to Clients of Amazon Business..
        description: | # this will include new lines to allow paragraphs
            I worked on contract for Amazon as an associate representative to assist Amazon Business Clients with various services and analysis' to foster oversight and optimization with relation to their procurement operations, finance and account management.

      - layout: left
        title: TPUSA Inc.
        link: https://www.teleperformance.com/en-us/
        link_text: TPUSA Inc.
        sub_title: Client Representative
        #caption: AO SMITH October 2015 - November 2016
        #caption: SimpliSafe August 2021 - February 2023
        #caption: Charles Schwab February 2023 - Present
        quote: >
          Adding value to our clients through exceptional service.
        description: | # this will include new lines to allow paragraphs
            I have had years of experience working on a diversity projects in support of a variety of clients in industries including but not limited to: Manufacturing, Home Security, Technology and Financial Services. Any mention of any organization, technology, product, service, or any other entity is for informational purposes only and does not constitute an endorsement or recommendation by TPUSA Inc or by it's clients, affiliates, partners, or subsidiaries.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: John S. Battle High School
        caption: 2009 - 2013
        sub_title: Advanced Studies Diploma
        quote: >
          Founded in 1959 and named for former Virginia Governor John S. Battle, John S. Battle High School has remained commited to being a center of acedemic excellence in the Commonwealth of Virginia.
        description: | # this will include new lines to allow paragraphs
          During my time at John Battle, I was enrolled as an Advanced Studies Student with Dual Enrollment status. I focused my studies on STEM related topics including but not limited to Physics, Chemisty, Computer Programming and other advanced studies in high level Maths.

          I spent a lot of my free time involved in extra curricular activities, volunteer service and developing my skills in Programming and Computer Science.

      - layout: left
        title: Codecademy
        caption: January 2023 - Present
        sub_title: Professional Certifications and Skills
        quote: >
          ..empowering all people, regardless of where they are in their coding journeys, to continue to learn, grow, and make an impact on the world around them.
        description: | # this will include new lines to allow paragraphs
          I am using Codecademy to continue my education in Computer Science and Programming. I am currently enrolled in the Full-Stack Engineer Professional Certification Program and other skill paths such as but not limited to:
          - Machine Learning / AI Engineering
          - Data Science : Natuarl Language Processing
          - Build Chatbots with Python
          - DevOps
          - Recommender Systems
          - and more!

      - layout: left
        title: Extra - Curriculars
        caption: 
        sub_title: various credentials, classes and extra-curricular studies
        quote: >
          ..a few extra things I picked up along the way or am currently pursuing in my spare time.
        description: | #this will include new lines to allow paragraphs
          CompTIA A+, NET+, SEC+,
          Harvard CS50 for Ai
          Unity Engine Certified User for Game Development
          Columbia Engineering Certificate of Completion Coding Bootcamp
          University of Richmond Certificate of Completion Data Science Bootcamp
          and more...

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      My research in Software Engineering and Emerging Technologies has been primarily focused on:
      - WebDev (HTML, CSS / Bootstrap, Flask - Python)
      - Ai (NLP, Reccomender Systems)
      - TinyML
      - XR / AR / VR / MR
      - Gaming Development
      - and Robotics

      Look at this cool image  
      ![Cosmic Art](/zahariromanov.github.io/docs/images/cosmicart.jpg "Cosmic Art")

# Footer
footer_show_references: true
references_title: References available upon request.
title_links:
  - title: Check me out on Kaggle!
    icon: fab fa-kaggle
    url: https://www.kaggle.com/zahariromanov/
    text: We are always looking to add quality talent to the team. If you are interested in working with us, please contact me at zahariromanov@pm.me . 

    
# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag